apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
data:
  DB_HOST: "mysql"                 # MySQL 서비스 이름
  DB_USER: "api_user"              # MySQL 사용자
  DB_PASSWORD: "password123" # MySQL 비밀번호
  DB_NAME: "mydatabase"            # MySQL 데이터베이스 이름
