apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: yoonheoz/api:1.0  # Docker 이미지 (컨테이너)
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-server-config  # ConfigMap에서 환경변수 가져오기
